"""initial_migration

Revision ID: 7a46e3036a3b
Revises: 
Create Date: 2026-08-25 18:05:31.884407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a46e3036a3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact_analysis', sa.Text(), nullable=True),
    sa.Column('recommendation_class', sa.String(length=50), nullable=True),
    sa.Column('wa_formatted_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_events_event_hash'), 'corporate_events', ['event_hash'], unique=True)
    op.create_index('ix_corporate_events_publication_date', 'corporate_events', ['publication_date'], unique=False)
    op.create_index(op.f('ix_corporate_events_ticker'), 'corporate_events', ['ticker'], unique=False)
    op.create_index('ix_corporate_events_ticker_event_type', 'corporate_events', ['ticker', 'event_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['corporate_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_event_id'), 'alert_logs', ['event_id'], unique=False)
    op.create_index('ix_alert_logs_phone_number', 'alert_logs', ['phone_number'], unique=False)
    op.create_index('ix_alert_logs_status', 'alert_logs', ['status'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_user_ticker_subscription')
    )
    op.create_index('ix_user_subscriptions_ticker', 'user_subscriptions', ['ticker'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_ticker', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index('ix_alert_logs_status', table_name='alert_logs')
    op.drop_index('ix_alert_logs_phone_number', table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_event_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_corporate_events_ticker_event_type', table_name='corporate_events')
    op.drop_index(op.f('ix_corporate_events_ticker'), table_name='corporate_events')
    op.drop_index('ix_corporate_events_publication_date', table_name='corporate_events')
    op.drop_index(op.f('ix_corporate_events_event_hash'), table_name='corporate_events')
    op.drop_table('corporate_events')
    # ### end Alembic commands ###
